### ISSUE TITLE
[3.1.01] Dedicated Server Crash when creating a BigReactor

### ISSUE THREAD

**Issue by Valdiralita** [TheBritishBrotherhood/ArdentCraft-The-Beginning#108]
When you put the final block into a BigReactor/ExtremeReactor the dedicated server crashes when it tries to resolve the multiblock structure.

https://hastebin.com/ehihijemaf.rb
```
java.lang.NoSuchMethodError: it.zerono.mods.zerocore.util.ItemHelper.createItemStack(Lnet/minecraft/block/state/IBlockState;I)Lnet/minecraft/item/ItemStack;
	at erogenousbeef.bigreactors.common.multiblock.MultiblockReactor.isBlockGoodForInterior(MultiblockReactor.java:686)
	at it.zerono.mods.zerocore.api.multiblock.rectangular.RectangularMultiblockControllerBase.isMachineWhole(RectangularMultiblockControllerBase.java:164)
	at erogenousbeef.bigreactors.common.multiblock.MultiblockReactor.isMachineWhole(MultiblockReactor.java:390)
	at it.zerono.mods.zerocore.api.multiblock.MultiblockControllerBase.checkIfMachineIsWhole(MultiblockControllerBase.java:381)
	at it.zerono.mods.zerocore.internal.common.MultiblockWorldRegistry.processMultiblockChanges(MultiblockWorldRegistry.java:242)
	at it.zerono.mods.zerocore.internal.common.MultiblockRegistry.tickStart(MultiblockRegistry.java:92)
	at it.zerono.mods.zerocore.internal.common.MultiblockEventHandler.onWorldTick(MultiblockEventHandler.java:32)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_MultiblockEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Valdiralita** [comment]
This is due to the use of Carbon Blocks inside of the reactor.

Bug is present in: ExtremeReactors-1.10.2-0.4.5.24.jar
**Bug is FIXED in:  ExtremeReactors-1.10.2-0.4.5.26.jar**

I suggest replacing the mod with its new version.
