### ISSUE TITLE
[3.1.01] Dedicated Server Crash when creating a QuantumQuarry

### ISSUE THREAD

**Issue by Valdiralita** [TheBritishBrotherhood/ArdentCraft-The-Beginning#109]
The Quantum Quarry form ExtraUtils2 creates a new world and mines it. It also prevents Mobs from spawning.
Then there comes LycanitesMobs and decided to spawn mobs when ore is mined.
ExtraUtils2 tries to prevent that by canceling the spawn event but its not cancelable so the server crashes.

We fixed it by removing LycanitesMobs.

related: [https://github.com/Lycanite/LycanitesMobs/issues/204](https://github.com/Lycanite/LycanitesMobs/issues/204)

https://hastebin.com/axifufehen.rb
`java.lang.IllegalArgumentException: Attempted to cancel a non cancellable event
	at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:93)
	at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.preventSpawn(WorldProviderSpecialDim.java:83)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1003_WorldProviderSpecialDim_preventSpawn_LivingSpawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:185)
	at lycanite.lycanitesmobs.core.spawning.SpawnTypeBase.spawnMobs(SpawnTypeBase.java:529)
	at lycanite.lycanitesmobs.core.spawning.SpawnTypeBlockBreak.spawnMobs(SpawnTypeBlockBreak.java:43)
	at lycanite.lycanitesmobs.core.spawning.CustomSpawner.onHarvestDrops(CustomSpawner.java:158)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_501_CustomSpawner_onHarvestDrops_HarvestDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:258)
	at net.minecraft.block.Block.func_180653_a(Block.java:545)
	at net.minecraft.block.BlockOre.func_180653_a(BlockOre.java:63)
	at net.minecraft.block.Block.func_176226_b(Block.java:537)
	at net.minecraft.block.Block.func_180657_a(Block.java:712)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:336)
	at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:291)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)`

**Comment by winterwurzel** [comment]
same thing happened to my server today, thanks for the temp fix!

crashlog: [https://hastebin.com/idoqawazeb.rb](https://hastebin.com/idoqawazeb.rb)
