### ISSUE TITLE
Crashes from Launcher

### ISSUE THREAD

**Issue by ripps818** [TheBritishBrotherhood/ArdentCraft-The-Beginning#73]
Using the modpack from the Curse Launcher, it will start the generic minecraft launcher, but when I hit _Play_ I get a bunch of error output.

Modpack: Ardentcraft The Beginning 2.7.0.1 Beta
OS: Windows 10 64-bit
CPU: Core i5-2400
GPU: Nvidia Geforce 750 ti
RAM: 16GB DDR3
JVM Args: -Xmx6G -Xms4G -XX:PermSize=1G -Dminecraft.applet.TargetDirectory="D:\ripps818\Documents\Curse\Minecraft\Instances\ArdentCraft The Beginning " -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

> 2017-01-15 23:37:38,947 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
> 2017-01-15 23:37:38,949 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
> [23:37:38] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
> [23:37:39] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
> [23:37:39] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
> [23:37:39] [main/INFO] [FML]: Forge Mod Loader version 12.18.3.2185 for Minecraft 1.10.2 loading
> [23:37:39] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_111, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_111
> [23:37:39] [main/WARN] [FML]: The coremod portablejim.additionalresources.Ar_CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [23:37:39] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [23:37:39] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [23:37:39] [main/WARN] [FML]: The coremod mekanism.common.launch.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: java.lang.NullPointerException
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.util.Objects.requireNonNull(Unknown Source)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.util.Arrays$ArrayList.<init>(Unknown Source)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.util.Arrays.asList(Unknown Source)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at mekanism.common.launch.DepLoader$DepLoadInst.modFiles(DepLoader.java:508)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at mekanism.common.launch.DepLoader$DepLoadInst.scanDepInfos(DepLoader.java:514)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at mekanism.common.launch.DepLoader$DepLoadInst.load(DepLoader.java:466)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at mekanism.common.launch.DepLoader.load(DepLoader.java:605)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at mekanism.common.launch.LoadingHook.<init>(LoadingHook.java:11)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.Class.newInstance(Unknown Source)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:593)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:423)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:253)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
> [23:37:39] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> [23:37:39] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at D:\ripps818\Documents\Curse\Minecraft\Instances\ArdentCraft The Beginning  for Forge Mod Loader
> java.lang.NullPointerException
> 	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_111]
> 	at java.util.Arrays$ArrayList.<init>(Unknown Source) ~[?:1.8.0_111]
> 	at java.util.Arrays.asList(Unknown Source) ~[?:1.8.0_111]
> 	at mekanism.common.launch.DepLoader$DepLoadInst.modFiles(DepLoader.java:508) ~[DepLoader$DepLoadInst.class:?]
> 	at mekanism.common.launch.DepLoader$DepLoadInst.scanDepInfos(DepLoader.java:514) ~[DepLoader$DepLoadInst.class:?]
> 	at mekanism.common.launch.DepLoader$DepLoadInst.load(DepLoader.java:466) ~[DepLoader$DepLoadInst.class:?]
> 	at mekanism.common.launch.DepLoader.load(DepLoader.java:605) ~[DepLoader.class:?]
> 	at mekanism.common.launch.LoadingHook.<init>(LoadingHook.java:11) ~[Mekanism-1.10.2-9.2.1.295.jar:?]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_111]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_111]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:593) ~[forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:423) ~[forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:253) ~[forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102) [forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79) [forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41) [forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138) [forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> [23:37:39] [main/ERROR] [LaunchWrapper]: Unable to launch
> java.lang.NullPointerException
> 	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_111]
> 	at java.util.Arrays$ArrayList.<init>(Unknown Source) ~[?:1.8.0_111]
> 	at java.util.Arrays.asList(Unknown Source) ~[?:1.8.0_111]
> 	at mekanism.common.launch.DepLoader$DepLoadInst.modFiles(DepLoader.java:508) ~[DepLoader$DepLoadInst.class:?]
> 	at mekanism.common.launch.DepLoader$DepLoadInst.scanDepInfos(DepLoader.java:514) ~[DepLoader$DepLoadInst.class:?]
> 	at mekanism.common.launch.DepLoader$DepLoadInst.load(DepLoader.java:466) ~[DepLoader$DepLoadInst.class:?]
> 	at mekanism.common.launch.DepLoader.load(DepLoader.java:605) ~[DepLoader.class:?]
> 	at mekanism.common.launch.LoadingHook.<init>(LoadingHook.java:11) ~[Mekanism-1.10.2-9.2.1.295.jar:?]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_111]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_111]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:593) ~[forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:423) ~[forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:253) ~[forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102) ~[forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79) ~[forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41) ~[forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138) ~[forge-1.10.2-12.18.3.2185.jar:?]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Exception in thread "main" [23:37:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
> [23:37:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
> [23:37:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
> [23:37:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
> [23:37:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
> [23:37:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
> [23:37:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>

**Comment by ripps818** [comment]
Nevermind, I completely deleted the pack and redownloaded everything and it seems to work now. Guess one of the mod downloads got corrupted somehow.
