### ISSUE TITLE
no more crashing, but stuck on bed

### ISSUE THREAD

**Issue by RupsjeNG** [TheBritishBrotherhood/ArdentCraft-The-Beginning#8]
hi... my game is like crashing all the time.. what can i do to fix that?

**Comment by drewcasebeer** [comment]
Not sure if its the same reason but appears to be happening from a EntityAbyssalZombie in abyssalcraft. Logs below

```Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: 4
    at com.shinoow.abyssalcraft.common.entity.EntityAbyssalZombie.func_180482_a(EntityAbyssalZombie.java:402)
    at com.shinoow.abyssalcraft.common.entity.EntityAbyssalZombie.func_70074_a(EntityAbyssalZombie.java:343)
    at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1064)
    at net.minecraft.entity.monster.EntityZombie.func_70645_a(EntityZombie.java:793)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970)
    at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73)
    at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:284)
    at net.minecraft.entity.monster.EntityMob.func_70652_k(SourceFile:111)
    at com.shinoow.abyssalcraft.common.entity.EntityAbyssalZombie.func_70652_k(EntityAbyssalZombie.java:223)
    at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:150)
    at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:139)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
    at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2189)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:47)
    at com.shinoow.abyssalcraft.common.entity.EntityAbyssalZombie.func_70636_d(EntityAbyssalZombie.java:217)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52)
    at net.minecraft.world.World.func_72866_a(World.java:1964)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
    at net.minecraft.world.World.func_72870_g(World.java:1934)
    at net.minecraft.world.World.func_72939_s(World.java:1750)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)```

**Comment by RupsjeNG** [comment]
i had no more crashing sinds the update. but now.. when i go and sleep i am stuck on the bed. if the bed is against a wall. not even esc is working. only close window and rstart my game is the option.

**Comment by TheBritishBrotherhood** [comment]
The Abyssalcraft crashes are now fixed!

The bed bug is a 1.10 issue, There is currently no fix for this.

I would look at getting a custom mod tho fix this issue in the future!

Also sorry for the late reply :P

**Comment by drewcasebeer** [comment]
Haha no worries and thanks for looking into it loving the pack so far!
